# permissions to do edit minimalgcps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: minimalgcp-editor-role
rules:
- apiGroups:
  - gcp.configurationstacks.crossplane.io
  resources:
  - minimalgcps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gcp.configurationstacks.crossplane.io
  resources:
  - minimalgcps/status
  verbs:
  - get
  - patch
  - update
