# permissions to do viewer minimalgcps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: minimalgcp-viewer-role
rules:
- apiGroups:
  - gcp.configurationstacks.crossplane.io
  resources:
  - minimalgcps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gcp.configurationstacks.crossplane.io
  resources:
  - minimalgcps/status
  verbs:
  - get
