# This file is used to define a custom transformer for our CRDs so that Kustomize
# can change the cross-resource object references when the referred object's
# name changes.
# See https://github.com/kubernetes-sigs/kustomize/blob/master/examples/transformerconfigs/crd/README.md
varReference:
  - path: spec/credentialsSecretRef/key
    kind: Provider
  - path: spec/credentialsSecretRef/name
    kind: Provider
  - path: spec/credentialsSecretRef/namespace
    kind: Provider
  - path: spec/projectID
    kind: Provider